version: '3'

services:

  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8080:80"
    depends_on:
      - app
    container_name: project_nginx

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    restart: always
    volumes:
      - ./:/var/www
    depends_on:
      - db
    container_name: project_app


  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: test-session
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_INITDB_ARGS: '--encoding=UTF8 --lc-collate=en_US.utf8 --lc-ctype=en_US.utf8'
    ports:
      - 5432:5432
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    container_name: project_db

  admin:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - 8077:8080


  pgadmin:
    container_name: db_pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"



